name: Code Quality

on: [push]

jobs:
    linting:
        name: Linting
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install
            - name: Code Linting
              run: npm run lint
    testing:
        name: Testing
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install
            - name: Unit Testing
              run: npm run test
            
